language: node_js

node_js:
    - 12.12.0

services: mongodb

before_install: 
  - cd backend

install:
  - npm install

jobs:
    include:
        - stage: test
          script: npm test
        - stage: deploy
          script: 
            - npm install -g serverless
            - npm install serverless-google-cloudfunctions
            - bash deploy.sh
