resources:
  - type: storage.v1.bucket
    name: sls-my-gcloud-service-dev-1605430108275
  - type: 'gcp-types/cloudfunctions-v1:projects.locations.functions'
    name: my-gcloud-service-dev-app
    properties:
      parent: projects/delta-vial-295117/locations/us-central1
      availableMemoryMb: 256
      runtime: nodejs8
      timeout: 60s
      entryPoint: app
      function: my-gcloud-service-dev-app
      sourceArchiveUrl: >-
        gs://sls-my-gcloud-service-dev-1605430108275/serverless/my-gcloud-service/dev/1605432915788-2020-11-15T09:35:15.788Z/my-gcloud-service.zip
      labels: {}
      httpsTrigger:
        url: path
